basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name=  'basicapp'

urlpatterns=[
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basicapp import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^basicapp/', include('basicapp.urls'))
]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': ' hello world', 'number': 100}
    return render(request, 'basicapp/index.html', context_dict)

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light"">
    <div class="container">
      <ul class="nav navbar-nav">
        <li ><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
        <li ><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
        <li ><a class="navbar-link" href="{% url 'basicapp:other' %}">Other</a></li>
      </ul>
    </div>
  </nav>
  <div class="container">

    {% block body_block %}
    <!-- Anything outside will be inherited -->
    {% endblock %}

  </div>
</body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html"%}
{% block body_block %}
<h1>Welcome to index</h1>
<h2>This is the index.html</h2>

<h1>{{text|cut:'world'}}</h1>
<h1>{{number|add:"99"}}</h1>

{% endblock%}

templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html"%}
{% block body_block %}
<h1>Welcome to other</h1>
<h2>This is an example of template inheritance</h2>
{% endblock%}

templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>Welcome to relative url tempalates</h1>
<a href="{% url 'basicapp:other' %}">other</a>
<a href="{% url 'admin:index'%}"> admin</a>
<a href="{% url 'index' %}">index</a>
  </body>
</html>